language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install
  - mysql -e 'CREATE DATABASE timeseries_test COLLATE utf8_unicode_ci;'
  - mysql timeseries_test < schema.mysql.sql

script:
  - vendor/bin/phpunit --coverage-text
