CREATE TABLE `timeseries` (
  `id`       INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`     VARCHAR(255)     NOT NULL,
  `timezone` VARCHAR(255)     NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_unicode_ci;

CREATE TABLE `timeseries_data` (
  `series_id` TINYINT(3) UNSIGNED NOT NULL,
  `start`     INT(10) UNSIGNED    NOT NULL,
  `end`       INT(10) UNSIGNED    NOT NULL,
  `qty`       DECIMAL(18, 9) DEFAULT NULL,
  PRIMARY KEY (`series_id`, `start`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_unicode_ci;

CREATE TABLE `timeseries_data_shard` (
  `series_id`       INT(10) UNSIGNED NOT NULL,
  `start_timestamp` INT(10) UNSIGNED NOT NULL,
  `interval_0`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_1`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_2`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_3`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_4`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_5`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_6`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_7`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_8`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_9`      DECIMAL(18, 9) DEFAULT NULL,
  `interval_10`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_11`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_12`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_13`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_14`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_15`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_16`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_17`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_18`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_19`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_20`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_21`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_22`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_23`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_24`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_25`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_26`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_27`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_28`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_29`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_30`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_31`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_32`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_33`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_34`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_35`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_36`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_37`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_38`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_39`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_40`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_41`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_42`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_43`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_44`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_45`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_46`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_47`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_48`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_49`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_50`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_51`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_52`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_53`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_54`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_55`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_56`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_57`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_58`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_59`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_60`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_61`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_62`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_63`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_64`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_65`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_66`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_67`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_68`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_69`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_70`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_71`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_72`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_73`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_74`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_75`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_76`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_77`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_78`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_79`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_80`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_81`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_82`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_83`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_84`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_85`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_86`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_87`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_88`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_89`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_90`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_91`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_92`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_93`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_94`     DECIMAL(18, 9) DEFAULT NULL,
  `interval_95`     DECIMAL(18, 9) DEFAULT NULL,
  PRIMARY KEY (`series_id`, `start_timestamp`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_unicode_ci;
